# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='heartbeat.proto',
  package='',
  serialized_pb=_b('\n\x0fheartbeat.proto\"*\n\x05heart\x12\x0e\n\x06region\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"/\n\nheart_back\x12\x0e\n\x06result\x18\x01 \x02(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEART = _descriptor.Descriptor(
  name='heart',
  full_name='heart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='region', full_name='heart.region', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='heart.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=61,
)


_HEART_BACK = _descriptor.Descriptor(
  name='heart_back',
  full_name='heart_back',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='heart_back.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='heart_back.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['heart'] = _HEART
DESCRIPTOR.message_types_by_name['heart_back'] = _HEART_BACK

heart = _reflection.GeneratedProtocolMessageType('heart', (_message.Message,), dict(
  DESCRIPTOR = _HEART,
  __module__ = 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:heart)
  ))
_sym_db.RegisterMessage(heart)

heart_back = _reflection.GeneratedProtocolMessageType('heart_back', (_message.Message,), dict(
  DESCRIPTOR = _HEART_BACK,
  __module__ = 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:heart_back)
  ))
_sym_db.RegisterMessage(heart_back)


# @@protoc_insertion_point(module_scope)
